// Dados simulados para desenvolvimento e demonstração
import { Comunidade, Noticia, Evento, Pastoral } from '@/types/wordpress'

// Comunidades REAIS - Capelania Jesus Bom Pastor
export const mockComunidades: Comunidade[] = [
  {
    id: 1,
    date: "2024-01-15T10:00:00",
    featured_media: 0,
    slug: 'comunidade-sao-lucas',
    title: { rendered: 'Comunidade São Lucas' },
    content: { rendered: '<p>A Comunidade São Lucas é um espaço de fé e acolhimento. Nossa comunidade se dedica à evangelização, formação espiritual e ação social, sempre buscando viver o Evangelho de Cristo.</p><p>Realizamos celebrações semanais, grupos de oração, catequese para crianças e adultos, além de atividades recreativas e pastorais específicas.</p>' },
    excerpt: { rendered: '<p>Comunidade de fé dedicada à evangelização e formação espiritual.</p>' },
    acf: {
      banner: 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?w=1920&h=800&fit=crop&q=80',
      logo: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=200&h=200&fit=crop',
      nome_padroeiro: 'São Lucas',
      endereco: 'Alameda Paulo César Santana, 1135',
      horarios_missa: 'Consulte a secretaria',
      telefone: '',
      responsavel: 'Padre Handley',
    },
  },
  {
    id: 2,
    date: "2024-01-15T10:00:00",
    featured_media: 0,
    slug: 'comunidade-santo-expedito',
    title: { rendered: 'Comunidade Santo Expedito' },
    content: { rendered: '<p>A Comunidade Santo Expedito é conhecida por sua devoção e fé. Somos uma família unida pela fé e pelo amor ao próximo, sempre prontos para servir.</p><p>Oferecemos formação continuada, grupos de oração e diversas atividades que fortalecem os laços comunitários e a vida espiritual.</p>' },
    excerpt: { rendered: '<p>Comunidade dedicada à devoção e ao serviço ao próximo.</p>' },
    acf: {
      banner: 'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=1920&h=800&fit=crop&q=80',
      logo: 'https://images.unsplash.com/photo-1548625149-fc4a29cf7092?w=200&h=200&fit=crop',
      nome_padroeiro: 'Santo Expedito',
      endereco: 'Alameda Deocleciano Martins, 55',
      horarios_missa: 'Domingos: 07:30',
      telefone: '',
      responsavel: 'Padre Handley',
    },
  },
  {
    id: 3,
    date: "2024-01-15T10:00:00",
    featured_media: 0,
    slug: 'comunidade-nossa-senhora-de-fatima',
    title: { rendered: 'Comunidade Nossa Senhora de Fátima' },
    content: { rendered: '<p>A Comunidade Nossa Senhora de Fátima, localizada no Assentamento Tangará, é um lugar de fé e esperança. Inspirados pela mensagem de Fátima, buscamos viver a devoção mariana e o chamado à conversão.</p><p>Desenvolvemos ações sociais, grupos de oração e catequese que fortalecem nossa comunidade.</p>' },
    excerpt: { rendered: '<p>Comunidade mariana dedicada à devoção e à conversão.</p>' },
    acf: {
      banner: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=1920&h=800&fit=crop&q=80',
      logo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      nome_padroeiro: 'Nossa Senhora de Fátima',
      endereco: 'Assentamento Tangará',
      horarios_missa: 'Consulte a secretaria',
      telefone: '',
      responsavel: '',
    },
  },
  {
    id: 4,
    date: "2024-01-15T10:00:00",
    featured_media: 0,
    slug: 'comunidade-nossa-senhora-aparecida',
    title: { rendered: 'Comunidade Nossa Senhora Aparecida' },
    content: { rendered: '<p>A Comunidade Nossa Senhora Aparecida, também situada no Assentamento Tangará, é um lugar de encontro com a Mãe Aparecida. Cultivamos a devoção mariana e o amor ao próximo.</p><p>Oferecemos celebrações, grupos de oração, catequese e ações sociais que expressam nossa fé.</p>' },
    excerpt: { rendered: '<p>Comunidade dedicada à devoção a Nossa Senhora Aparecida.</p>' },
    acf: {
      banner: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&h=800&fit=crop&q=80',
      logo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
      nome_padroeiro: 'Nossa Senhora Aparecida',
      endereco: 'Assentamento Tangará',
      horarios_missa: 'Consulte a secretaria',
      telefone: '',
      responsavel: 'Padre Handley',
    },
  },
]

// Notícias REAIS + simuladas
export const mockNoticias: Noticia[] = [
  {
    id: 1,
    slug: 'galinhada-beneficente-09-novembro',
    title: { rendered: 'Convite Especial: Galinhada Beneficente dia 09/11' },
    content: { rendered: '<p>A Capelania Jesus Bom Pastor convida toda a comunidade para a Galinhada Beneficente que acontecerá no dia 09 de novembro, às 11:00 da manhã, no Seminário São José!</p><p>Esta é uma oportunidade maravilhosa de confraternização e solidariedade. Toda a renda será destinada ao acabamento da nossa igreja, ajudando-nos a tornar nosso templo ainda mais bonito e acolhedor.</p><p>O valor do ingresso é apenas R$ 15,00. Venha com sua família e amigos! Será um momento de muita alegria, boa comida e união em prol de uma causa nobre.</p><p>Contamos com a presença de todos! 🙏</p>' },
    excerpt: { rendered: '<p>Venha participar da Galinhada Beneficente no dia 09/11 e ajude no acabamento da igreja!</p>' },
    date: '2024-11-06T10:00:00',
    featured_media: 0,
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1598511757337-fe2cafc31ba0?w=800&h=600&fit=crop',
      categoria: 'Eventos',
      autor: 'Equipe de Comunicação',
    },
  },
  {
    id: 2,
    slug: 'encontro-das-familias-outubro',
    title: { rendered: 'Encontro das Famílias: Momento de Fé e União' },
    content: { rendered: '<p>Foi realizado no dia 19 de outubro um emocionante Encontro das Famílias da nossa capelania! Dezenas de famílias se reuniram para um momento especial de partilha, oração e fortalecimento dos laços fraternos.</p><p>O encontro contou com dinâmicas de integração, reflexões sobre a família cristã, momentos de oração em família e uma celebração eucarística muito especial.</p><p>As crianças também tiveram espaço com atividades recreativas e catequese lúdica. Foi um dia abençoado que renovou o compromisso das famílias com a fé e a vida comunitária.</p><p>Agradecemos a todos que participaram e organizaram este lindo encontro! Que Deus abençoe cada família! 🙏👨‍👩‍👧‍👦</p>' },
    excerpt: { rendered: '<p>Encontro das Famílias reuniu dezenas de famílias em momento de fé e união.</p>' },
    date: '2024-10-19T15:00:00',
    featured_media: 0,
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=800&h=600&fit=crop',
      categoria: 'Pastoral Familiar',
      autor: 'Pastoral Familiar',
    },
  },
  {
    id: 3,
    slug: 'costelada-beneficente-outubro',
    title: { rendered: 'Costelada Beneficente: Sucesso Total!' },
    content: { rendered: '<p>A Costelada Beneficente realizada no dia 15 de outubro foi um verdadeiro sucesso! Centenas de pessoas compareceram para saborear uma deliciosa costela e apoiar os projetos sociais da nossa capelania.</p><p>O evento contou com música ao vivo, atividades para as crianças e muita confraternização. A alegria e o espírito de solidariedade foram marcas deste dia especial.</p><p>Toda a renda arrecadada será destinada às ações sociais da Pastoral da Caridade, beneficiando famílias em situação de vulnerabilidade.</p><p>Agradecemos imensamente a todos que contribuíram: organizadores, voluntários e participantes. Deus abençoe cada gesto de generosidade! ❤️</p>' },
    excerpt: { rendered: '<p>Costelada beneficente arrecadou fundos para projetos sociais da capelania.</p>' },
    date: '2024-10-15T12:00:00',
    featured_media: 0,
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop',
      categoria: 'Eventos',
      autor: 'Equipe de Comunicação',
    },
  },
  {
    id: 4,
    slug: 'retiro-de-carnaval-2025',
    title: { rendered: 'Retiro de Carnaval 2025: Inscrições Abertas' },
    content: { rendered: '<p>Estão abertas as inscrições para o Retiro de Carnaval 2025! Este ano o tema será "Renovar a Esperança: Um Caminho de Fé e Comunhão".</p><p>O retiro acontecerá de 28 de fevereiro a 4 de março, na Casa de Retiros São José, em um ambiente de oração, reflexão e fraternidade.</p><p>Programação inclui: palestras com padres convidados, momentos de adoração, confissões, dinâmicas de grupo, caminhadas contemplativas e celebrações eucarísticas.</p><p>Investimento: R$ 350,00 (inclui hospedagem, alimentação e material). Vagas limitadas!</p>' },
    excerpt: { rendered: '<p>Inscrições abertas para o Retiro de Carnaval 2025. Tema: "Renovar a Esperança".</p>' },
    date: '2025-01-15T10:00:00',
    featured_media: 0,
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&h=600&fit=crop',
      categoria: 'Eventos',
      autor: 'Equipe de Comunicação',
    },
  },
  {
    id: 2,
    slug: 'nova-pastoral-da-juventude',
    title: { rendered: 'Lançamento da Nova Pastoral da Juventude' },
    content: { rendered: '<p>Com grande alegria, anunciamos o lançamento da renovada Pastoral da Juventude da Capelania Jesus Bom Pastor!</p><p>A PJ tem como missão acompanhar os jovens em sua caminhada de fé, promovendo encontros, retiros, grupos de oração e ações sociais.</p><p>O primeiro encontro será no dia 20 de janeiro, às 19h, no salão paroquial da Comunidade São José. Todos os jovens de 15 a 29 anos estão convidados!</p><p>Venha fazer parte dessa família e descobrir o plano de Deus para sua vida!</p>' },
    excerpt: { rendered: '<p>Nova Pastoral da Juventude será lançada em janeiro. Jovens de 15 a 29 anos, participem!</p>' },
    date: '2025-01-10T14:30:00',
    featured_media: 0,
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&h=600&fit=crop',
      categoria: 'Pastorais',
      autor: 'Padre João Silva',
    },
  },
  {
    id: 3,
    slug: 'campanha-solidaria-inverno',
    title: { rendered: 'Campanha Solidária de Inverno Arrecada 500 Cobertores' },
    content: { rendered: '<p>A Campanha Solidária de Inverno da Capelania foi um grande sucesso! Graças à generosidade de nossa comunidade, arrecadamos mais de 500 cobertores, 300 peças de roupas de frio e 200 kg de alimentos não perecíveis.</p><p>Todo o material arrecadado foi distribuído para famílias em situação de vulnerabilidade social nas comunidades do entorno e em abrigos da cidade.</p><p>Agradecemos a todos que colaboraram com esta corrente de solidariedade. Que o Senhor abençoe cada gesto de amor!</p>' },
    excerpt: { rendered: '<p>Campanha de inverno arrecadou 500 cobertores e beneficiou dezenas de famílias.</p>' },
    date: '2025-01-05T09:00:00',
    featured_media: 0,
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&h=600&fit=crop',
      categoria: 'Ação Social',
      autor: 'Pastoral da Caridade',
    },
  },
  {
    id: 4,
    slug: 'formacao-catequistas-2025',
    title: { rendered: 'Curso de Formação para Catequistas 2025' },
    content: { rendered: '<p>Está com inscrições abertas o Curso de Formação para Catequistas 2025! O curso é destinado a todos que desejam atuar na catequese ou aprofundar seu conhecimento sobre a fé católica.</p><p>Serão 10 encontros aos sábados, das 14h às 17h, com início em 25 de janeiro. Os temas incluem: Bíblia, Doutrina, Liturgia, Pedagogia Catequética e Espiritualidade do Catequista.</p><p>Certificado reconhecido pela Diocese. Investimento: R$ 80,00 (material incluso).</p><p>Inscrições na secretaria paroquial ou pelo WhatsApp (34) 99999-9999.</p>' },
    excerpt: { rendered: '<p>Curso de formação para catequistas inicia em janeiro. Inscreva-se!</p>' },
    date: '2025-01-02T16:00:00',
    featured_media: 0,
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&h=600&fit=crop',
      categoria: 'Formação',
      autor: 'Coordenação de Catequese',
    },
  },
  {
    id: 5,
    slug: 'celebracao-ano-novo',
    title: { rendered: 'Celebração de Ano Novo Reúne Centenas de Fiéis' },
    content: { rendered: '<p>A Missa de Ação de Graças pelo Ano Novo, realizada no dia 1º de janeiro, reuniu centenas de fiéis em uma celebração emocionante e repleta de fé.</p><p>O Padre João Silva, em sua homilia, destacou a importância de iniciar o ano confiando na providência divina e renovando o compromisso com o Evangelho.</p><p>Após a celebração, houve confraternização com café da manhã comunitário, momento de partilha e alegria entre as famílias.</p><p>Que 2025 seja um ano de bênçãos, paz e crescimento espiritual para todos!</p>' },
    excerpt: { rendered: '<p>Missa de Ano Novo reuniu centenas de fiéis em celebração emocionante.</p>' },
    date: '2025-01-01T11:00:00',
    featured_media: 0,
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1482575832494-771f74bf6857?w=800&h=600&fit=crop',
      categoria: 'Celebrações',
      autor: 'Equipe de Comunicação',
    },
  },
  {
    id: 6,
    slug: 'encontro-casais-fevereiro',
    title: { rendered: 'Encontro de Casais: Fortalecendo o Amor no Matrimônio' },
    content: { rendered: '<p>A Pastoral Familiar convida todos os casais para um encontro especial sobre "Fortalecendo o Amor no Matrimônio", que acontecerá no dia 14 de fevereiro (Dia dos Namorados), das 19h às 22h.</p><p>O encontro contará com palestra do casal Marcos e Ana Paula, que compartilharão sua experiência de 25 anos de casamento, dinâmicas de casal, momento de oração e renovação das promessas matrimoniais.</p><p>Haverá também um jantar romântico preparado especialmente para os casais. Inscrições antecipadas são necessárias.</p>' },
    excerpt: { rendered: '<p>Encontro especial para casais no Dia dos Namorados. Inscreva-se!</p>' },
    date: '2024-12-28T10:00:00',
    featured_media: 0,
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=800&h=600&fit=crop',
      categoria: 'Pastoral Familiar',
      autor: 'Pastoral Familiar',
    },
  },
]

// Eventos REAIS + simulados
export const mockEventos: Evento[] = [
  {
    id: 1,
    slug: 'galinhada-beneficente',
    title: { rendered: 'Galinhada Beneficente' },
    content: { rendered: '<p>Galinhada em benefício do acabamento da igreja! Venha apoiar esta causa importante e saborear uma deliciosa galinhada preparada com carinho pela nossa comunidade.</p><p>Toda a renda será revertida para as obras de acabamento da igreja, ajudando-nos a tornar nosso templo ainda mais bonito e acolhedor para as celebrações.</p><p>Ingresso: R$ 15,00 | Horário: 11:00 | Local: Seminário São José</p>' },
    excerpt: { rendered: '<p>Galinhada beneficente para o acabamento da igreja.</p>' },
    date: '2024-11-09T11:00:00',
    featured_media: 0,
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1598511757337-fe2cafc31ba0?w=800&h=600&fit=crop',
      data_inicio: '2024-11-09',
      data_fim: '2024-11-09',
      hora_inicio: '11:00',
      hora_fim: '15:00',
      local: 'Seminário São José',
      valor: 'R$ 15,00',
      organizador: 'Comissão de Festas',
    },
  },
  {
    id: 2,
    slug: 'missa-solene-padroeiro',
    title: { rendered: 'Missa Solene do Padroeiro' },
    content: { rendered: '<p>Celebração solene em honra ao nosso padroeiro Jesus Bom Pastor. Missa presidida pelo Bispo Diocesano, seguida de procissão e festa comunitária.</p><p>Programação: 17h - Terço e Cânticos | 18h - Missa Solene | 19h30 - Procissão | 20h - Festa com barracas, música e confraternização.</p>' },
    excerpt: { rendered: '<p>Celebração solene do padroeiro com missa, procissão e festa.</p>' },
    date: '2025-04-20T18:00:00',
    featured_media: 0,
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=800&h=600&fit=crop',
      data_inicio: '2025-04-20',
      data_fim: '2025-04-20',
      hora_inicio: '18:00',
      hora_fim: '22:00',
      local: 'Igreja Matriz - Comunidade São Lucas',
      organizador: 'Comissão de Festas',
    },
  },
  {
    id: 2,
    slug: 'retiro-quaresma-2025',
    title: { rendered: 'Retiro de Quaresma 2025' },
    content: { rendered: '<p>Retiro quaresmal com o tema "Do Deserto à Ressurreição: Um Caminho de Conversão". Três dias de oração, reflexão e renovação espiritual.</p><p>Inclui: palestras, adoração ao Santíssimo, Via Sacra, confissões, dinâmicas de grupo e celebração penitencial.</p>' },
    excerpt: { rendered: '<p>Retiro de três dias para viver intensamente a Quaresma.</p>' },
    date: '2025-03-14T18:00:00',
    featured_media: 0,
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&h=600&fit=crop',
      data_evento: '2025-03-14',
      hora_evento: '18:00',
      local_evento: 'Casa de Retiros São José',
      organizador: 'Equipe de Formação',
    },
  },
  {
    id: 3,
    slug: 'encontro-jovens-marco',
    title: { rendered: 'Encontro de Jovens: "Jovem, Levanta-te!"' },
    content: { rendered: '<p>Grande encontro da Pastoral da Juventude com palestras, música, testemunhos e celebração eucarística. Tema: "Jovem, Levanta-te! - Descobrindo seu chamado".</p><p>Palestrantes convidados, bandas católicas, food trucks e muito mais!</p>' },
    excerpt: { rendered: '<p>Encontro de jovens com música, palestras e celebração.</p>' },
    date: '2025-03-22T14:00:00',
    featured_media: 0,
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&h=600&fit=crop',
      data_evento: '2025-03-22',
      hora_evento: '14:00',
      local_evento: 'Ginásio Poliesportivo',
      organizador: 'Pastoral da Juventude',
    },
  },
  {
    id: 4,
    slug: 'festa-junina-2025',
    title: { rendered: 'Festa Junina da Capelania 2025' },
    content: { rendered: '<p>A tradicional Festa Junina da Capelania está chegando! Três dias de festa com barracas típicas, quadrilha, música ao vivo, brincadeiras e muita diversão para toda a família.</p><p>Toda a renda será revertida para as obras sociais da Capelania.</p>' },
    excerpt: { rendered: '<p>Festa Junina tradicional com três dias de muita diversão.</p>' },
    date: '2025-06-20T18:00:00',
    featured_media: 0,
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&h=600&fit=crop',
      data_evento: '2025-06-20',
      hora_evento: '18:00',
      local_evento: 'Pátio da Igreja Matriz',
      organizador: 'Comissão de Festas',
    },
  },
  {
    id: 5,
    slug: 'caminhada-pela-vida',
    title: { rendered: 'Caminhada pela Vida e pela Paz' },
    content: { rendered: '<p>Caminhada ecumênica em defesa da vida, da paz e da justiça social. Concentração às 8h com café da manhã comunitário, saída às 9h.</p><p>Percurso de 5km pelas principais ruas da cidade, com paradas para reflexão e oração.</p>' },
    excerpt: { rendered: '<p>Caminhada ecumênica em defesa da vida e da paz.</p>' },
    date: '2025-05-10T08:00:00',
    featured_media: 0,
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop',
      data_evento: '2025-05-10',
      hora_evento: '08:00',
      local_evento: 'Praça Central (concentração)',
      organizador: 'Pastoral Social',
    },
  },
]

// Pastorais simuladas
export const mockPastorais: Pastoral[] = [
  {
    id: 1,
    date: "2024-01-15T10:00:00",
    featured_media: 0,
    slug: 'pastoral-familiar',
    title: { rendered: 'Pastoral Familiar' },
    content: { rendered: '<p>A Pastoral Familiar acompanha as famílias em sua caminhada de fé, promovendo encontros, cursos de preparação matrimonial, grupos de casais e ações que fortalecem os vínculos familiares.</p><p>Missão: Ser presença evangelizadora junto às famílias, ajudando-as a viver o amor cristão no cotidiano.</p><p>Atividades: Encontros mensais de casais, curso de noivos, batizado de casamentos, grupos de apoio, palestras sobre educação dos filhos.</p>' },
    excerpt: { rendered: '<p>Acompanhamento e evangelização das famílias cristãs.</p>' },
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=800&h=600&fit=crop',
      coordenador: 'Casal Marcos e Ana Paula Silva',
      contato: '(34) 99111-2222',
      horario_reuniao: 'Primeira sexta-feira do mês, 19h30',
    },
  },
  {
    id: 2,
    date: "2024-01-15T10:00:00",
    featured_media: 0,
    slug: 'pastoral-da-juventude',
    title: { rendered: 'Pastoral da Juventude' },
    content: { rendered: '<p>A Pastoral da Juventude é um espaço de encontro, formação e missão para jovens de 15 a 29 anos. Buscamos formar jovens protagonistas, conscientes de sua fé e comprometidos com a transformação da sociedade.</p><p>Missão: Evangelizar os jovens e com os jovens, promovendo seu crescimento humano e espiritual.</p><p>Atividades: Encontros semanais, retiros, acampamentos, ações sociais, grupos de oração, eventos culturais.</p>' },
    excerpt: { rendered: '<p>Formação e evangelização de jovens de 15 a 29 anos.</p>' },
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&h=600&fit=crop',
      coordenador: 'Lucas Ferreira e Maria Eduarda Costa',
      contato: '(34) 99222-3333',
      horario_reuniao: 'Sábados, 19h',
    },
  },
  {
    id: 3,
    date: "2024-01-15T10:00:00",
    featured_media: 0,
    slug: 'pastoral-da-crianca',
    title: { rendered: 'Pastoral da Criança' },
    content: { rendered: '<p>A Pastoral da Criança desenvolve ações básicas de saúde, nutrição, educação e cidadania com famílias de crianças de 0 a 6 anos em situação de vulnerabilidade.</p><p>Missão: Promover o desenvolvimento integral das crianças, desde a concepção até os seis anos de idade, em seu contexto familiar e comunitário.</p><p>Atividades: Visitas domiciliares, acompanhamento do desenvolvimento infantil, orientação nutricional, celebração da vida.</p>' },
    excerpt: { rendered: '<p>Desenvolvimento integral de crianças de 0 a 6 anos.</p>' },
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=600&fit=crop',
      coordenador: 'Carla Mendes',
      contato: '(34) 99333-4444',
      horario_reuniao: 'Segundas-feiras, 14h',
    },
  },
  {
    id: 4,
    date: "2024-01-15T10:00:00",
    featured_media: 0,
    slug: 'pastoral-da-caridade',
    title: { rendered: 'Pastoral da Caridade' },
    content: { rendered: '<p>A Pastoral da Caridade promove ações de solidariedade e assistência às pessoas em situação de vulnerabilidade social, vivendo o mandamento do amor ao próximo.</p><p>Missão: Ser sinal do amor de Deus através do serviço aos mais necessitados.</p><p>Atividades: Distribuição de cestas básicas, visita a enfermos, apoio a moradores de rua, campanhas solidárias, bazar beneficente.</p>' },
    excerpt: { rendered: '<p>Ações de solidariedade e assistência aos necessitados.</p>' },
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&h=600&fit=crop',
      coordenador: 'José Carlos Santos',
      contato: '(34) 99444-5555',
      horario_reuniao: 'Quartas-feiras, 19h',
    },
  },
  {
    id: 5,
    date: "2024-01-15T10:00:00",
    featured_media: 0,
    slug: 'pastoral-liturgica',
    title: { rendered: 'Pastoral Litúrgica' },
    content: { rendered: '<p>A Pastoral Litúrgica cuida da preparação e animação das celebrações litúrgicas, promovendo a participação ativa e consciente de toda a assembleia.</p><p>Missão: Zelar pela dignidade das celebrações e formar a comunidade para uma vivência litúrgica autêntica.</p><p>Atividades: Formação de ministros, preparação de celebrações, coordenação dos coroinhas, ornamentação da igreja.</p>' },
    excerpt: { rendered: '<p>Preparação e animação das celebrações litúrgicas.</p>' },
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?w=800&h=600&fit=crop',
      coordenador: 'Padre João Silva',
      contato: '(34) 99555-6666',
      horario_reuniao: 'Quintas-feiras, 20h',
    },
  },
  {
    id: 6,
    date: "2024-01-15T10:00:00",
    featured_media: 0,
    slug: 'pastoral-catequese',
    title: { rendered: 'Pastoral da Catequese' },
    content: { rendered: '<p>A Pastoral da Catequese promove a educação na fé através de processos catequéticos para crianças, adolescentes e adultos, preparando para os sacramentos.</p><p>Missão: Anunciar Jesus Cristo e formar discípulos missionários através da catequese.</p><p>Atividades: Catequese infantil, crisma, catequese de adultos, formação de catequistas, celebrações catequéticas.</p>' },
    excerpt: { rendered: '<p>Educação na fé e preparação para os sacramentos.</p>' },
    acf: {
      imagem_destaque: 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=800&h=600&fit=crop',
      coordenador: 'Irmã Beatriz Almeida',
      contato: '(34) 99666-7777',
      horario_reuniao: 'Sábados, 15h',
    },
  },
]

